#' ---
#' title: "Analysis of xenium epilepsy data"
#' author: "Mathias Delhaye"
#' date: "2025-02-11"
#' output: github_document
#' ---
#'
#' This script is intended to analyze the megadata generated by Dr. Larissa Krauss, obtained using the 10X genomics Xenium technology.
#' Samples: FFPE human hippocampus sections resected from patients with epilepsy and postmortem surgery


#' Load libraries needed

library(tidyverse)
library(Seurat)
library(ggplot2)
library(here)
library(future)

# get the working directory
path = here()

# read the megadata
megadata = read_rds(file.path(str_remove(path,"xenium_epilepsy_repo"),"REALfull_QC_RCTD_clust_processed.rds"))

